// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proje.Models;

namespace Proje.Migrations
{
    [DbContext(typeof(AgencyContext))]
    [Migration("20201212124632_databseCreation")]
    partial class databseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Proje.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.HasIndex("CountryCode");

                    b.HasIndex("TourId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Proje.Models.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryCode");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Proje.Models.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TourId");

                    b.HasIndex("CountryCode");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Proje.Models.City", b =>
                {
                    b.HasOne("Proje.Models.Country", "country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.HasOne("Proje.Models.Tour", "tour")
                        .WithMany()
                        .HasForeignKey("TourId");

                    b.Navigation("country");

                    b.Navigation("tour");
                });

            modelBuilder.Entity("Proje.Models.Tour", b =>
                {
                    b.HasOne("Proje.Models.Country", "country")
                        .WithMany()
                        .HasForeignKey("CountryCode");

                    b.Navigation("country");
                });
#pragma warning restore 612, 618
        }
    }
}
